name: Build Caddy Docker Image

on:
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-docker.yml'
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'   # daily check for new Caddy
  workflow_dispatch:

concurrency:
  group: caddy-build
  cancel-in-progress: true

permissions:
  contents: write     # for auto-bump commit
  packages: write     # REQUIRED for pushing to GHCR

jobs:
  check-caddy-version:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.get.outputs.version }}
      changed: ${{ steps.compare.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - name: Get latest Caddy release (stable)
        id: get
        run: |
          v=$(curl -fsSL https://api.github.com/repos/caddyserver/caddy/releases/latest \
             | jq -r 'select(.prerelease==false) | .tag_name' | sed 's/^v//')
          echo "version=$v" >> $GITHUB_OUTPUT

      - name: Read current version from Dockerfile
        id: cur
        run: |
          cur=$(grep -E '^ARG CADDY_VERSION=' Dockerfile | cut -d= -f2)
          echo "version=$cur" >> $GITHUB_OUTPUT

      - name: Compare
        id: compare
        run: |
          if [ "${{ steps.get.outputs.version }}" != "${{ steps.cur.outputs.version }}" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-caddy-version
    if: github.event_name != 'schedule' || needs.check-caddy-version.outputs.changed == 'true'
    steps:
      - uses: actions/checkout@v4

      - name: Auto-bump CADDY_VERSION (if changed)
        if: needs.check-caddy-version.outputs.changed == 'true'
        run: |
          v="${{ needs.check-caddy-version.outputs.latest }}"
          sed -i "s/^ARG CADDY_VERSION=.*/ARG CADDY_VERSION=${v}/" Dockerfile
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: bump CADDY_VERSION to ${v}" || true
          git push || true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags/labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          # IMPORTANT: ghcr image name is lowercase
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ needs.check-caddy-version.outputs.latest }}
            type=ref,event=branch
            type=sha,prefix=git-,format=short

      - name: Build and push (multi-arch, SBOM/provenance)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
